const en = {
  header: {
    home: "Home",
    services: "Services",
    products: "Products",
    caseStudies: "Case Studies",
    company: "Company",
    career: "Career",
    contact: "Contact",
    english: "ENGLISH",
    kurdish: "Kurdish",
    anyBusinessIdea: "ANY BUSYNESS IDEA",
  },
  footer: {
    titleAboutNewroz: "About Newroz",
    aboutNewrozDetails:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dictum aliquet accumsan porta lectus ridiculus in mattis. Netus sodales in volutpat ullamcorper amet adipiscing fermentum.",
    titleAbout: "About",
    titleSoftwareEngineering: "Software Engineering",
    titleCentersofExcellence: "Centers of Excellence",
    aboutUs: "About us",
    blog: "Blog",
    careers: "Careers",
    jobs: "Jobs",
    Portfolio: "Portfolio",
    webAppDevelopment: "Web App Development",
    mobileAppDevelopment: "Mobile App Development",
    cloudConsultancy: "Cloud Consultancy",
    customSoftwareDevelopment: "Custom Software Development",
    inPress: "In Press",
    technicalDebtReduction: "Technical Debt Reduction",
    roboticProcessAutomation: "Robotic Process Automation",
    aIAndMachineLearning: "AI & Machine Learning",
    chatbots: "Chatbots",
    contact: "Contact",
    privacyPolicy: "Privacy policy",
    sitemap: "Sitemap",
    termsOfUse: "Terms of Use",
    allRightsReserved: "All Rights Reserved",
  },
  homeTopSetion: {
    title: "Empowering",
    subtitle: "BUSINESSES WITH ADVANCED TECHNOLOGY",
    details:
      "We are a team of passionate individuals who go the extra mile to create wonderful experiences for your business.",
    connectWithUs: "CONNECT WITH US",
    howItWorks: "How it works",
  },
};

export default en;
