const fr = {
  header: {
    home: "بيت",
    services: "خدمات",
    products: "منتجات",
    caseStudies: "دراسات الحالة",
    company: "شركة",
    career: "حياة مهنية",
    contact: "اتصال",
    english: "ENGLISH",
    kurdish: "Kurdish",
    anyBusinessIdea: "أي فكرة عمل",
  },
  footer: {
    titleAboutNewroz: "Newroz عن",
    aboutNewrozDetails:
      "العميل مهم جدا ، العميل سيتبعه. لا يوجد شيء مثل شاحنة ذات طبقات في العقار. أعضاء Netus في حياة ullamcorper amet adipiscing fermentum.",
    titleAbout: "عن",
    titleSoftwareEngineering: "هندسة البرمجيات",
    titleCentersofExcellence: "مراكز التميز",
    aboutUs: "معلومات عنا",
    blog: "مدونة",
    careers: "وظائف",
    jobs: "وظائف",
    Portfolio: "ورقة الملف الشخصي",
    webAppDevelopment: "تطوير تطبيقات الويب ",
    mobileAppDevelopment: "تطوير تطبيقات الجوال",
    cloudConsultancy: "الاستشارات السحابية",
    customSoftwareDevelopment: "تطوير البرمجيات المخصصة",
    inPress: "في الصحافة",
    technicalDebtReduction: "تخفيض الديون الفنية",
    roboticProcessAutomation: "أتمتة العمليات الروبوتية",
    aIAndMachineLearning: "AI & Machine Learning",
    chatbots: "الذكاء الاصطناعي والتعلم الآلي",
    contact: "معلومات",
    privacyPolicy: "سياسة الخصوصية",
    sitemap: "خريطة الموقع",
    termsOfUse: "شروط الاستخدام",
    allRightsReserved: "كل الحقوق محفوظة",
  },
  homeTopSetion: {
    title: "التمكين",
    subtitle: "الأعمال مع التكنولوجيا المتقدمة",
    details:
      "نحن فريق من الأفراد المتحمسين الذين يذهبون إلى أبعد من ذلك لخلق تجارب رائعة لعملك.",
    connectWithUs: "اتصل بنا",
    howItWorks: "كيف تعمل",
    animationText: "We are here to help you achieve your success.",
  },
};
export default fr;
